function res = uAnalytical(x, y, u1Zero, u2Zero, mu)

    % automatically generated by sympy

    if mu == -1
        u1 = -u1Zero * sin(x) / tan(1) + u1Zero * sin(x) / sin(1) +...
            u1Zero * cos(x) + x .* sin(x) / 2 + x .* exp(-4 * x) / 17 -...
            sin(x) / 2 - 25 * sin(x) / (289 * exp(4) * sin(1)) +...
            8 * sin(x) / (289 * tan(1)) - 8 * cos(x) / 289 +...
            8 * exp(-4 * x) / 289;

        u2 = (4225 * u2Zero + (632 - 4225 * u2Zero) * cos(1) - 506 * exp(2) * sin(2) +...
            408 * exp(2) * cos(2)) * sin(y) +...
            (130 * y .* exp(2 * y) .* sin(2 * y) -...
            1040 * y .* exp(2 * y) .* cos(2 * y) +...
            (4225 * u2Zero - 632) * cos(y) + 376 * exp(2 * y) .* sin(2 * y) +...
            632 * exp(2 * y) .* cos(2 * y)) * sin(1);
        u2 = u2 / (4225 * sin(1));

    elseif mu == 16
        u1 = (-u1Zero.*exp(8) + u1Zero.*exp(4) - x.*(1 - exp(8))*(4*x + 1)/64 + (-1088*u1Zero.*exp(4) + 1088*u1Zero - 64*exp(4)*cos(1) - 21).*exp(8*x)/1088 - (1 - exp(8))*exp(4*x).*cos(x)/17 - exp(8)/17 + 5/64 + exp(4)*cos(1)/17).*exp(-4*x)/(1 - exp(8));

        u2 = (-20*y.*sin(2*y) - 10*y.*cos(2*y) + sin(2*y) - 7*cos(2*y)).*exp(2*y)/200 + (-200*u2Zero.*exp(4) + 200*u2Zero - 19*exp(6)*sin(2) + 7 - 17*exp(6)*cos(2)).*exp(4*y)/(200*(1 - exp(8))) - (-200*u2Zero.*exp(4) + 200*u2Zero - 7*exp(4) + 17*exp(2)*cos(2) + 19*exp(2)*sin(2)).*exp(-4*y)/(400*sinh(4)); 
    else
        u1 =  -x.*exp(-4*x)./(mu - 16) + (mu.^3.*u1Zero.*exp(sqrt(mu) + 4) - mu.^3.*u1Zero.*exp(4) - 31*mu.^2.*u1Zero.*exp(sqrt(mu) + 4) + 31*mu.^2.*u1Zero.*exp(4) + mu.^2.*exp(sqrt(mu)) + mu.^2.*exp(sqrt(mu) + 4).*cos(1) - mu.^2.*exp(4) + 224*mu.*u1Zero.*exp(sqrt(mu) + 4) - 224*mu.*u1Zero.*exp(4) - 23*mu.*exp(sqrt(mu)) - 32*mu.*exp(sqrt(mu) + 4).*cos(1) + 40*mu.*exp(4) + 256*u1Zero.*exp(sqrt(mu) + 4) - 256*u1Zero.*exp(4) - 24*exp(sqrt(mu)) + 256*exp(sqrt(mu) + 4).*cos(1) - 248*exp(4)).*exp(-4)*exp(sqrt(mu).*x)./(mu.^3.*exp(2*sqrt(mu)) - mu.^3 - 31*mu.^2.*exp(2*sqrt(mu)) + 31*mu.^2 + 224*mu.*exp(2*sqrt(mu)) - 224*mu + 256*exp(2*sqrt(mu)) - 256) + (mu.^3.*u1Zero.*exp(sqrt(mu) + 4) - mu.^3.*u1Zero.*exp(4) - 31*mu.^2.*u1Zero.*exp(sqrt(mu) + 4) + 31*mu.^2.*u1Zero.*exp(4) + mu.^2.*exp(sqrt(mu) + 4) - mu.^2.*exp(4)*cos(1) - mu.^2 + 224*mu.*u1Zero.*exp(sqrt(mu) + 4) - 224*mu.*u1Zero.*exp(4) - 40*mu.*exp(sqrt(mu) + 4) + 23*mu + 32*mu.*exp(4)*cos(1) + 256*u1Zero.*exp(sqrt(mu) + 4) - 256*u1Zero.*exp(4) + 248*exp(sqrt(mu) + 4) - 256*exp(4)*cos(1) + 24).*exp(-sqrt(mu).*x).*exp(sqrt(mu) - 4)./(mu.^3.*exp(2*sqrt(mu)) - mu.^3 - 31*mu.^2.*exp(2*sqrt(mu)) + 31*mu.^2 + 224*mu.*exp(2*sqrt(mu)) - 224*mu + 256*exp(2*sqrt(mu)) - 256) - cos(x)./(mu + 1) + 8*exp(-4*x)./(mu - 16).^2;

        u2 = -8*mu.^2.*exp(2*y).*sin(2*y)./(mu.^4 + 128*mu.^2 + 4096) - 8*mu.^2.*exp(2*y).*cos(2*y)./(mu.^4 + 128*mu.^2 + 4096) - 2*mu.*y.*exp(2*y).*sin(2*y)./(mu.^2 + 64) + 128*mu.*exp(2*y).*sin(2*y)./(mu.^4 + 128*mu.^2 + 4096) - 128*mu.*exp(2*y).*cos(2*y)./(mu.^4 + 128*mu.^2 + 4096) - 16*y.*exp(2*y).*cos(2*y)./(mu.^2 + 64) + (mu.^4.*u2Zero.*exp(sqrt(mu)) - mu.^4.*u2Zero - 2*mu.^3.*exp(2)*sin(2) + 128*mu.^2.*u2Zero.*exp(sqrt(mu)) - 128*mu.^2.*u2Zero + 8*mu.^2.*exp(sqrt(mu)) - 8*mu.^2.*exp(2)*sin(2) - 24*mu.^2.*exp(2)*cos(2) + 128*mu.*exp(sqrt(mu)) - 128*mu.*exp(2)*cos(2) + 4096*u2Zero.*exp(sqrt(mu)) - 4096*u2Zero - 512*exp(sqrt(mu)) - 512*sqrt(2)*exp(2)*cos(pi/4 + 2)).*exp(sqrt(mu)).*exp(-sqrt(mu).*y)./(mu.^4.*exp(2*sqrt(mu)) - mu.^4 + 128*mu.^2.*exp(2*sqrt(mu)) - 128*mu.^2 + 4096*exp(2*sqrt(mu)) - 4096) + (mu.^4.*u2Zero.*exp(sqrt(mu)) - mu.^4.*u2Zero + 2*mu.^3.*exp(sqrt(mu) + 2).*sin(2) + 128*mu.^2.*u2Zero.*exp(sqrt(mu)) - 128*mu.^2.*u2Zero + 24*mu.^2.*exp(sqrt(mu) + 2).*cos(2) + 8*mu.^2.*exp(sqrt(mu) + 2).*sin(2) - 8*mu.^2 + 128*mu.*exp(sqrt(mu) + 2).*cos(2) - 128*mu + 4096*u2Zero.*exp(sqrt(mu)) - 4096*u2Zero + 512*sqrt(2)*exp(sqrt(mu) + 2).*cos(pi/4 + 2) + 512).*exp(sqrt(mu).*y)./(mu.^4.*exp(2*sqrt(mu)) - mu.^4 + 128*mu.^2.*exp(2*sqrt(mu)) - 128*mu.^2 + 4096*exp(2*sqrt(mu)) - 4096) + 512*exp(2*y).*sin(2*y)./(mu.^4 + 128*mu.^2 + 4096) + 512*exp(2*y).*cos(2*y)./(mu.^4 + 128*mu.^2 + 4096);
    end
    
    res = u1 + u2;
end
